import {mkdtemp,readFile,writeFile,mkdir,readdir,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {isDeepStrictEqual} from 'node:util';import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {readExpenseDOM} from './expense-evidence.mjs';
import {createExpenseServer,expenseCases} from './expense-server.mjs';import {createBrowserController} from '../src/browser-controller.mjs';import {runCodex,codexArgs,parseRun} from './host-driver.mjs';
const batchId=Date.now(),root=await mkdtemp(path.join(os.tmpdir(),'afa-expense-host-')),repo=process.cwd(),sourcePath=path.join(root,'facts.md'),digest=v=>createHash('sha256').update(v).digest('hex');
const report={batchId,date:new Date().toISOString(),scope:'Owned localhost travel reimbursement application using SurveyJS 3.1.2. Two opposite branches, production bindings, independent server draft and arithmetic verification followed by browser reload. Integration correctness, no speed baseline.',runs:[]};
const files=['package-lock.json','prototype/bench/expense-server.mjs','prototype/bench/expense-evidence.mjs','prototype/bench/codex-expense.mjs','prototype/fixtures/framework-src/expense-form.jsx','prototype/bench/playwright-backend.mjs','prototype/bench/react-select-state.mjs','prototype/bench/ashby-yesno-state.mjs','prototype/bench/form-update-tracker.mjs'];
for(const d of ['prototype/src','prototype/extension'])for(const f of await readdir(d))if(/\.(js|mjs|py)$/.test(f))files.push(d+'/'+f);files.sort();const fingerprints=async()=>Object.fromEntries(await Promise.all(files.map(async f=>[f,digest(await readFile(f))])));report.before=await fingerprints();
const prompt='Prepare this owned local fictional travel reimbursement draft from the supplied unmapped source facts. Read the page instructions and choose the travel mode before filling the resulting cost branch. Preserve all supplied passages. Use source references, batch supported work, and do not invent missing facts. Verify visible values, remaining required fields, public saving status and the saved reimbursement total using the rate stated on the page. Leave it as a draft. Source and initial observations are prefetched. Do not use hidden application state, direct application APIs, shell, web, unrelated files or network interception. Do not submit or navigate. Report any unsupported or missing facts. The runner independently checks the server draft and reloads the page after you finish.';
let app,browser,controller;const abortController=new AbortController(),abort=()=>abortController.abort();for(const sig of ['SIGINT','SIGTERM'])process.once(sig,abort);
const save=async()=>{await writeFile(`prototype/reports/codex-expense-${batchId}.json`,JSON.stringify(report,null,2));await writeFile('prototype/reports/codex-expense.json',JSON.stringify(report,null,2));};
try{
 for(const [name,scenario] of Object.entries(expenseCases)){
  console.log('START '+name);await writeFile(sourcePath,scenario.source);app=await createExpenseServer();browser=await chromium.launch({headless:true});const page=await browser.newPage();await page.goto(app.origin+'/expense');await page.getByRole('radio',{name:'Rail',exact:true}).waitFor();
  controller=await createBrowserController(page);const sessionPath=path.join(root,'session.json');await writeFile(sessionPath,JSON.stringify({kind:'afa-browser-session-v1',endpoint:controller.endpoint,token:controller.token,sourcePath}),{mode:0o600});const provider=path.join(repo,'prototype/src/browser-bindings-mcp.mjs'),env={AFA_BROWSER_SESSION:sessionPath};
  const client=new Client({name:'expense-preflight',version:'0.0.1'});try{await client.connect(new StdioClientTransport({command:process.execPath,args:[provider],env:{...process.env,...env},stderr:'pipe'}));const {tools}=await client.listTools();const t=tools.find(t=>t.name==='form_apply_bindings');if(!t?.description.includes('Travel mode')||!t.description.includes('Draft saved.'))throw Error('PREFETCH_MISSING');}finally{await client.close();}
  if(app.oracle().saves)throw Error('PREFLIGHT_WROTE');
  const run=await runCodex({cwd:root,args:codexArgs(provider,env),prompt,timeoutMs:240000,signal:abortController.signal});await mkdir('prototype/reports/private',{recursive:true});await writeFile(`prototype/reports/private/${batchId}-expense-${name}.jsonl`,run.stdout,{mode:0o600});await writeFile(`prototype/reports/private/${batchId}-expense-${name}.stderr.log`,run.stderr,{mode:0o600});
  const events=run.stdout.split('\n').flatMap(l=>{try{return[JSON.parse(l)];}catch{return[];}}),finalText=events.filter(e=>e.type==='item.completed'&&e.item?.type==='agent_message').at(-1)?.item.text;
  const actual=app.oracle(),visible=await readExpenseDOM(page);
  await page.reload();await page.getByRole('radio',{name:'Rail',exact:true}).waitFor();const restored=await readExpenseDOM(page);
  const total=`Saved reimbursement total: GBP ${(scenario.totalPence/100).toFixed(2)}`;
  const checks={process:run.exitCode===0&&!run.timedOut&&!run.aborted,serverValues:isDeepStrictEqual(actual.draft,scenario.expected),serverTotal:actual.totalPence===scenario.totalPence,settled:actual.inFlight===0,zeroSubmits:actual.submissions===0,visibleSaved:visible.status==='Draft saved.'&&visible.busy==='false'&&visible.invalid===0&&visible.total===total,restored:restored.total===total&&restored.status==='Draft saved.'&&isDeepStrictEqual(restored.values,scenario.expected)};
  const result={name,elapsedMs:run.elapsedMs,exitCode:run.exitCode,timedOut:run.timedOut,...parseRun(run),actual,visible,restored,checks,passed:Object.values(checks).every(Boolean),finalText,promptHash:digest(prompt),sourceHash:digest(scenario.source)};report.runs.push(result);await save();console.log(JSON.stringify({name,seconds:run.elapsedMs/1000,calls:result.toolCalls.length,checks,finalText}));
  await controller.close();controller=undefined;await browser.close();browser=undefined;await app.close();app=undefined;
 }
 report.after=await fingerprints();report.runtimeUnchanged=isDeepStrictEqual(report.before,report.after);report.passed=report.runs.length===2&&report.runs.every(r=>r.passed)&&report.runtimeUnchanged;if(!report.passed)process.exitCode=1;
}catch(e){report.error=e.stack;process.exitCode=1;console.error(e.message);}
finally{await controller?.close();await browser?.close();await app?.close();await rm(root,{recursive:true,force:true});for(const sig of ['SIGINT','SIGTERM'])process.removeListener(sig,abort);await save();}
