import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {createHarness} from './harness.mjs';
import {createPlaywrightBackend} from './playwright-backend.mjs';
import {createDocumentSession} from '../src/document-session.mjs';
import {projectRoot} from '../src/bridge.mjs';
import {aliasQueries,aliasBindings,aliasOracle} from './alias-cases.mjs';
import '../scripts/build-fixtures.mjs';
const h=await createHarness(),request=createPlaywrightBackend(h.page).request,results=[];
const setup=async()=>{await h.reset('alias-form');await h.page.waitForSelector('[role=combobox]');const session=await createDocumentSession({sourcePath:`${projectRoot}/prototype/fixtures/documents/alias-candidate.md`,request});const context=await session.context();return {session,context,queries:aliasQueries(context)};};
const check=async(name,fn)=>{try{await fn();results.push({name,passed:true});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}};
try{
 await check('batch discovery returns qualified choices without selecting or leaving queries',async()=>{const {session,context,queries}=await setup();const r=await session.search({url:context.page.url,queries});assert.deepEqual(r.searches.map(s=>s.options.length),[1,2,1]);assert.ok(r.searches[1].options.some(o=>o.label.endsWith('Nanjing campus')));const state=await h.page.evaluate(()=>window.applicationState);assert.equal(state.city,'');assert.equal(state.schools[0].school,'');assert.equal(await h.page.locator('[role=listbox]').count(),0);assert.ok(r.page.fields.filter(f=>f.kind==='autocomplete').every(f=>!f.query));});
 await check('unknown option references reject before any write',async()=>{const {session,context,queries}=await setup();await assert.rejects(session.apply({url:context.page.url,bindings:{[queries[0].ref]:queries[0].sourceId},choices:{[queries[0].ref]:{optionRef:'invented'}}}),/INVALID_OPTION_REFERENCE/);assert.equal(await h.page.evaluate(()=>window.applicationState.city),'');});
 await check('option reference cannot be reused for another source fact',async()=>{const {session,context,queries}=await setup();const r=await session.search({url:context.page.url,queries:[queries[0]]});await assert.rejects(session.apply({url:context.page.url,bindings:{[queries[0].ref]:queries[1].sourceId},choices:{[queries[0].ref]:{optionRef:r.searches[0].options[0].optionRef}}}),/INVALID_OPTION_REFERENCE/);});
 await check('refresh invalidates old choice references',async()=>{const {session,context,queries}=await setup();const r=await session.search({url:context.page.url,queries:[queries[0]]});await session.context();await assert.rejects(session.apply({url:context.page.url,bindings:{[queries[0].ref]:queries[0].sourceId},choices:{[queries[0].ref]:{optionRef:r.searches[0].options[0].optionRef}}}),/INVALID_OPTION_REFERENCE/);});
 await check('choice is re-queried and disappearance stops selection',async()=>{const {session,context,queries}=await setup();const r=await session.search({url:context.page.url,queries:[queries[0]]});await h.page.evaluate(()=>window.emptySearch=true);const a=await session.apply({url:context.page.url,bindings:{[queries[0].ref]:queries[0].sourceId},choices:{[queries[0].ref]:{optionRef:r.searches[0].options[0].optionRef}}});assert.equal(a.complete,false);assert.equal(await h.page.evaluate(()=>window.applicationState.city),'');});
 await check('identical visible labels remain ambiguous after discovery',async()=>{const {session,context,queries}=await setup();await h.page.evaluate(()=>window.duplicateSearch=true);const r=await session.search({url:context.page.url,queries:[queries[0]]});assert.equal(r.searches[0].options.length,2);const a=await session.apply({url:context.page.url,bindings:{[queries[0].ref]:queries[0].sourceId},choices:{[queries[0].ref]:{optionRef:r.searches[0].options[0].optionRef}}});assert.equal(a.complete,false);assert.equal(a.reason,'OPTION_MISSING_OR_AMBIGUOUS');assert.equal(await h.page.evaluate(()=>window.applicationState.city),'');});
 await check('all queries validate before any search event',async()=>{const {session,context,queries}=await setup();await assert.rejects(session.search({url:context.page.url,queries:[queries[0],{...queries[1],sourceId:'unknown'}]}),/UNKNOWN_SOURCE/);assert.equal(await h.page.evaluate(()=>window.searchRequests.length),0);await assert.rejects(session.search({url:context.page.url,queries:Array.from({length:13},()=>queries[0])}),/1–12/);});
 await check('multiple terms for one source retain all returned option refs',async()=>{const {session,context,queries}=await setup();const q=queries[0];const r=await session.search({url:context.page.url,queries:[q,{...q,query:'hang'}]});const a=await session.apply({url:context.page.url,bindings:{[q.ref]:q.sourceId},choices:{[q.ref]:{optionRef:r.searches[0].options[0].optionRef}}});assert.equal(a.complete,true);});
 await check('discovery preserves an existing selected entity',async()=>{const {session,context,queries}=await setup();const q=queries[0];const r=await session.search({url:context.page.url,queries:[q]});await session.apply({url:context.page.url,bindings:{[q.ref]:q.sourceId},choices:{[q.ref]:{optionRef:r.searches[0].options[0].optionRef}}});const next=await session.search({url:context.page.url,queries:[{...q,query:'Beijing'}]});assert.equal(next.searches[0].status,'observed');assert.equal(await h.page.evaluate(()=>window.applicationState.city),'hz');});
 await check('requested-target success explicitly reports uncovered required fields',async()=>{const {session,context}=await setup();const f=context.page.fields.find(f=>f.label==='Applicant name'),entry=context.source.entries.find(e=>e.label==='姓名');const r=await session.apply({url:context.page.url,bindings:{[f.ref]:entry.id}});assert.equal(r.complete,true);assert.equal(r.completionScope,'requested-targets');assert.equal(r.coverage.visibleRequiredCovered,false);assert.ok(r.coverage.unresolvedRequired.some(f=>f.label==='Earliest available start date'));});
 await check('known facts fill across repeated choices; missing required fact remains explicit',async()=>{const {session,context,queries}=await setup();const discovered=await session.search({url:context.page.url,queries});const r=await session.apply(aliasBindings(discovered,discovered.searches));assert.equal(r.complete,true,JSON.stringify(r));assert.equal(r.coverage.visibleRequiredCovered,false);assert.deepEqual(r.coverage.unresolvedRequired.map(f=>f.label),['Earliest available start date']);assert.equal((await aliasOracle(h.page,context.source.entries.find(e=>e.label==='个人介绍').value)).passed,true);});
 await check('later DOM edits invalidate previously verified coverage',async()=>{const {session,context}=await setup();const f=context.page.fields.find(f=>f.label==='Applicant name'),entry=context.source.entries.find(e=>e.label==='姓名');await session.apply({url:context.page.url,bindings:{[f.ref]:entry.id}});await h.page.getByLabel('Applicant name',{exact:true}).fill('changed');const r=await session.context();assert.ok(r.coverage.unresolvedRequired.some(f=>f.label==='Applicant name'));});
}finally{await h.close();await writeFile(`${projectRoot}/prototype/reports/discovery-checks.json`,JSON.stringify({date:new Date().toISOString(),results},null,2));}
if(results.some(r=>!r.passed))process.exitCode=1;
