import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHarness} from './harness.mjs';
import {createDocumentSession} from '../src/document-session.mjs';
import {projectRoot} from '../src/bridge.mjs';
import '../scripts/build-fixtures.mjs';
const h=await createHarness(),results=[];
const reset=async()=>{await h.reset('react-form');await h.page.waitForSelector('input');return h.bridge.request({op:'inspect'});};
const check=async(name,fn)=>{try{const details=await fn();results.push({name,passed:true,...details});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}};
const goal=(o,fields)=>h.bridge.request({op:'goal',url:o.url,snapshot:o.snapshot,fields});
try{
 await check('React controlled inputs update actual component state',async()=>{const o=await reset();const r=await goal(o,[{group:'',label:'Applicant name',value:'林示例'}]);assert.equal(r.complete,true);assert.equal(await h.page.evaluate(()=>window.applicationState.fullName),'林示例');});
 await check('select-only Radix buttons are observed as fields',async()=>{const o=await reset();assert.equal(o.fields.filter(f=>f.kind==='combobox'&&f.supported).length,3);assert.equal(o.controls.length,1);assert.equal(o.fields.find(f=>f.label==='Preferred office city').disabled,true);});
 await check('Radix portal options use local keyboard selection and React state',async()=>{const o=await reset();const r=await goal(o,[{group:'',label:'Qualification level',value:'硕士'}]);assert.equal(r.complete,true,JSON.stringify(r));assert.equal(await h.page.evaluate(()=>window.applicationState.degree),'pg');assert.equal(await h.page.locator('[role=listbox]').count(),0);});
 await check('same goal waits for a dependent remounted city combobox',async()=>{const o=await reset();const r=await goal(o,[{group:'',label:'Country of residence',value:'中国'},{group:'',label:'Preferred office city',value:'杭州'}]);assert.equal(r.complete,true,JSON.stringify(r));const state=await h.page.evaluate(()=>window.applicationState);assert.equal(state.country,'cn');assert.equal(state.city,'hz');return {elapsedMs:r.elapsedMs,primitiveCalls:r.primitiveCalls};});
 await check('700ms successful validation is awaited without repeated typing',async()=>{const o=await reset();const r=await goal(o,[{group:'',label:'Email address',value:'candidate@example.test'}]);assert.equal(r.complete,true);assert.ok(r.elapsedMs>=700);assert.deepEqual(await h.page.evaluate(()=>window.validationState),{checking:false,invalid:false,loading:false});assert.equal(r.trace.filter(t=>t.operation==='fill').length,1);return {elapsedMs:r.elapsedMs};});
 await check('700ms rejected email cannot be reported as complete',async()=>{const o=await reset();const r=await goal(o,[{group:'',label:'Email address',value:'bad@invalid.example'}]);assert.equal(r.complete,false);assert.equal(r.reason,'VALIDATION_FAILED');assert.equal(await h.page.evaluate(()=>window.validationState.invalid),true);return{reason:r.reason,elapsedMs:r.elapsedMs};});
 await check('busy field has a bounded timeout rather than false success',async()=>{const o=await reset();await h.page.getByLabel('Applicant name',{exact:true}).evaluate(el=>el.setAttribute('aria-busy','true'));const r=await goal(o,[{group:'',label:'Applicant name',value:'林示例'}]);assert.equal(r.complete,false);assert.equal(r.reason,'FIELDS_NOT_READY');assert.equal(await h.page.evaluate(()=>window.applicationState.fullName),'');});
 await check('unknown and disabled options return choices without selecting',async()=>{for(const value of ['不存在','博士']){const o=await reset();const r=await goal(o,[{group:'',label:'Qualification level',value}]);assert.equal(r.complete,false);assert.equal(r.reason,'OPTION_MISSING_OR_AMBIGUOUS');assert.equal(await h.page.evaluate(()=>window.applicationState.degree),'');assert.equal(await h.page.locator('[role=listbox]').count(),0);assert.ok(r.observation.fields.find(f=>f.label==='Qualification level').options.some(o=>o.label==='硕士'));}});
 await check('duplicate option labels stop instead of choosing the first',async()=>{const o=await reset();await h.page.evaluate(()=>{const mo=new MutationObserver(()=>{const item=document.querySelectorAll('[role=option]')[1];if(item){mo.disconnect();item.parentElement.append(item.cloneNode(true));}});mo.observe(document.body,{subtree:true,childList:true});});const r=await goal(o,[{group:'',label:'Qualification level',value:'硕士'}]);assert.equal(r.complete,false);assert.equal(r.reason,'OPTION_MISSING_OR_AMBIGUOUS');assert.equal(await h.page.evaluate(()=>window.applicationState.degree),'');});
 await check('keyboard selection survives mouse pointer mode',async()=>{const o=await reset();await h.page.evaluate(()=>{const mo=new MutationObserver(()=>{const item=document.querySelectorAll('[role=option]')[1];if(item){mo.disconnect();item.dispatchEvent(new PointerEvent('pointermove',{pointerType:'mouse',bubbles:true}));}});mo.observe(document.body,{subtree:true,childList:true});});const r=await goal(o,[{group:'',label:'Qualification level',value:'硕士'}]);assert.equal(r.complete,true,JSON.stringify(r));assert.equal(await h.page.evaluate(()=>window.applicationState.degree),'pg');});
 await check('disabled fieldset descendants are not written',async()=>{await reset();await h.page.locator('fieldset').evaluate(el=>el.disabled=true);const o=await h.bridge.request({op:'inspect'});assert.equal(o.fields.find(f=>f.label==='Institution').disabled,true);const r=await goal(o,[{group:'Education 1',label:'Institution',value:'学校'}]);assert.equal(r.complete,false);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('editable combobox remains unsupported',async()=>{const o=await reset();await h.page.getByLabel('Applicant name',{exact:true}).evaluate(el=>{el.setAttribute('role','combobox');el.setAttribute('aria-autocomplete','list');});const fresh=await h.bridge.request({op:'inspect'});const f=fresh.fields.find(f=>f.label==='Applicant name');assert.equal(f.kind,'unsupported-combobox');assert.equal(f.supported,false);});
 await check('document expansion refreshes refs before both education bindings',async()=>{
  await reset();const session=await createDocumentSession({sourcePath:`${projectRoot}/prototype/fixtures/documents/framework-candidate.md`,request:r=>h.bridge.request(r)});const first=await session.context();const context=await session.expand({url:first.page.url,controlRef:first.page.controls[0].ref});
  assert.ok(context.page.fields.some(f=>f.group==='Education 2'));
  const bindings={},defs=[['','Applicant name','姓名'],['','Email address','邮箱'],['','Country of residence','居住国家'],['','Preferred office city','意向工作城市'],['','Qualification level','学历层次'],['','Personal statement','个人介绍'],['Education 1','Institution','学校','第一段教育经历'],['Education 1','Subject','专业','第一段教育经历'],['Education 2','Institution','学校','第二段教育经历'],['Education 2','Subject','专业','第二段教育经历']];
  for(const[group,label,sourceLabel,section]of defs){const f=context.page.fields.find(f=>f.group===group&&f.label===label),entry=context.source.entries.find(e=>e.label===sourceLabel&&(!section||e.context.endsWith(section)));assert.ok(f&&entry);bindings[f.ref]=entry.id;}
  const r=await session.apply({url:context.page.url,bindings});assert.equal(r.complete,true,JSON.stringify(r));const state=await h.page.evaluate(()=>({data:window.applicationState,submitted:window.submissionCount,validation:window.validationState}));assert.deepEqual(state.data.schools,[{school:'南方示例学院',major:'软件工程'},{school:'北方示例大学',major:'计算机科学'}]);assert.equal(state.data.country,'cn');assert.equal(state.data.city,'hz');assert.equal(state.data.degree,'pg');assert.equal(state.data.fullName,'林示例');assert.equal(state.data.email,'candidate@example.test');assert.equal(state.data.summary,context.source.entries.find(e=>e.label==='个人介绍').value);assert.equal(state.submitted,0);assert.equal(state.validation.checking,false);assert.equal(state.validation.invalid,false);
 });
 await check('source bindings can fill a repeated template in one goal',async()=>{
  await reset();const session=await createDocumentSession({sourcePath:`${projectRoot}/prototype/fixtures/documents/framework-candidate.md`,request:r=>h.bridge.request(r)});const {source,page}=await session.context();
  const refs=page.fields.filter(f=>f.group==='Education 1'),binding=Object.fromEntries(refs.map(f=>[f.ref,source.entries.find(e=>e.label===(f.label==='Institution'?'学校':'专业')&&e.context.endsWith('第二段教育经历')).id]));
  const r=await session.apply({url:page.url,bindings:{},repeatGroups:[{templateGroup:'Education 1',expectGroup:'Education 2',controlRef:page.controls[0].ref,bindings:binding}]});assert.equal(r.complete,true,JSON.stringify(r));assert.deepEqual(await h.page.evaluate(()=>window.applicationState.schools[1]),{school:'北方示例大学',major:'计算机科学'});assert.equal(r.trace.filter(t=>t.operation==='expand').length,1);
 });
 await check('a new repeated field with different kind is not filled',async()=>{
  await reset();const session=await createDocumentSession({sourcePath:`${projectRoot}/prototype/fixtures/documents/framework-candidate.md`,request:r=>h.bridge.request(r)});const {source,page}=await session.context();const f=page.fields.find(f=>f.group==='Education 1'&&f.label==='Institution');
  await h.page.evaluate(()=>{const mo=new MutationObserver(()=>{const fieldset=[...document.querySelectorAll('fieldset')].find(f=>f.querySelector('legend')?.textContent==='Education 2');if(fieldset){mo.disconnect();fieldset.querySelector('input').type='number';}});mo.observe(document.body,{subtree:true,childList:true});});
  const r=await session.apply({url:page.url,bindings:{},repeatGroups:[{templateGroup:'Education 1',expectGroup:'Education 2',controlRef:page.controls[0].ref,bindings:{[f.ref]:source.entries.find(e=>e.label==='学校').id}}]});assert.equal(r.complete,false);assert.equal(r.reason,'FIELD_KIND_CHANGED');assert.equal(await h.page.evaluate(()=>window.applicationState.schools[1].school),'');
 });
 await check('unknown template refs and arbitrary add controls fail before expansion',async()=>{
  await reset();const session=await createDocumentSession({sourcePath:`${projectRoot}/prototype/fixtures/documents/framework-candidate.md`,request:r=>h.bridge.request(r)});const {source,page}=await session.context();const f=page.fields.find(f=>f.label==='Applicant name');
  await assert.rejects(session.apply({url:page.url,bindings:{},repeatGroups:[{templateGroup:'Education 1',expectGroup:'Education 2',controlRef:page.controls[0].ref,bindings:{[f.ref]:source.entries[0].id}}]}),/WRONG_TEMPLATE_GROUP/);
  await assert.rejects(session.expand({url:page.url,controlRef:'submit'}),/UNOBSERVED_ADD_CONTROL/);assert.equal(await h.page.locator('fieldset').count(),1);assert.equal(await h.page.evaluate(()=>window.submissionCount),0);
 });

}finally{await h.close();await writeFile(`${projectRoot}/prototype/reports/framework-checks.json`,JSON.stringify({date:new Date().toISOString(),framework:'React 19.3.0 + Radix Select 2.3.7',results},null,2));}
if(results.some(r=>!r.passed))process.exitCode=1;
