import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {createHarness} from './harness.mjs';
import {createPlaywrightBackend} from './playwright-backend.mjs';
import {createDocumentSession} from '../src/document-session.mjs';
import {projectRoot} from '../src/bridge.mjs';
import '../scripts/build-fixtures.mjs';
const h=await createHarness(),request=createPlaywrightBackend(h.page,{validationMode:process.env.AFA_VALIDATION_MODE??'full'}).request,results=[];
const reset=async(suffix='')=>{await h.reset('search-form');if(suffix)await h.page.goto(h.page.url()+suffix);await h.page.waitForSelector('[role=combobox]');return request({op:'inspect'});};
const school=async o=>request({op:'goal',url:o.url,snapshot:o.snapshot,fields:[{group:'Education 1',label:'Institution',kind:'autocomplete',value:'南方示例学院'}]});
const check=async(name,fn)=>{try{const details=await fn();results.push({name,passed:true,...details});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}};
try {
 await check('recognizes two visible prefixed single-select search fields',async()=>{const o=await reset();assert.equal(o.fields.filter(f=>f.kind==='autocomplete').length,2);assert.ok(o.fields.filter(f=>f.kind==='autocomplete').every(f=>f.value===''));});
 await check('typed search text is not a selected entity or valid completion',async()=>{await reset();await h.page.getByLabel('Institution',{exact:true}).fill('南方示例学院');const o=await request({op:'inspect'}),f=o.fields.find(f=>f.label==='Institution');assert.equal(f.value,'');assert.equal(f.query,'南方示例学院');assert.equal(f.valid,false);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('450ms search waits for result and commits actual entity ID',async()=>{const o=await reset(),r=await school(o);assert.equal(r.complete,true,JSON.stringify(r));assert.ok(r.elapsedMs>=450);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'school-south');assert.equal(await h.page.locator('[role=listbox]').count(),0);return{elapsedMs:r.elapsedMs};});
 await check('already selected value needs no new search or input',async()=>{const o=await reset();await school(o);const before=await h.page.evaluate(()=>window.searchRequests.length);const fresh=await request({op:'inspect'});assert.equal((await school(fresh)).complete,true);assert.equal(await h.page.evaluate(()=>window.searchRequests.length),before);});
 await check('unknown search returns without selecting',async()=>{const o=await reset();const r=await request({op:'goal',url:o.url,snapshot:o.snapshot,fields:[{group:'Education 1',label:'Institution',value:'不存在的学院'}]});assert.equal(r.complete,false);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');assert.equal(await h.page.locator('[role=listbox]').count(),0);});
 await check('disabled search option is not selected',async()=>{const o=await reset();const r=await request({op:'goal',url:o.url,snapshot:o.snapshot,fields:[{group:'Education 1',label:'Institution',value:'停用学校'}]});assert.equal(r.complete,false);assert.equal(r.reason,'OPTION_MISSING_OR_AMBIGUOUS');assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('two exact labels stop instead of choosing first',async()=>{const o=await reset();await h.page.evaluate(()=>window.duplicateSearch=true);const r=await school(o);assert.equal(r.complete,false);assert.equal(r.reason,'OPTION_MISSING_OR_AMBIGUOUS');assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('slow search exhausts bounded readiness budget',async()=>{const o=await reset();await h.page.evaluate(()=>window.searchDelay=3000);const r=await school(o);assert.equal(r.complete,false);assert.ok(r.elapsedMs<2800);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('field relabel during search stops before any selection',async()=>{const o=await reset();await h.page.evaluate(()=>{const el=document.getElementById('school-0');el.addEventListener('input',()=>setTimeout(()=>el.setAttribute('aria-label','Different question'),50),{once:true});});const r=await school(o);assert.equal(r.complete,false);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('100ms application rejection cannot become final success',async()=>{const o=await reset();await h.page.evaluate(()=>window.rejectSelection=true);const r=await school(o);assert.equal(r.complete,false);assert.equal(await h.page.evaluate(()=>window.applicationState.schools[0].school),'');});
 await check('unrelated matching listbox is never used',async()=>{const o=await reset();await h.page.evaluate(()=>{window.unrelatedClicks=0;const n=document.createElement('div');n.setAttribute('role','listbox');n.innerHTML='<div role="option">南方示例学院</div>';n.onclick=()=>window.unrelatedClicks++;document.body.append(n);});const r=await school(o);assert.equal(r.complete,true,JSON.stringify(r));assert.equal(await h.page.evaluate(()=>window.unrelatedClicks),0);});
 await check('different documented class prefix is recognized',async()=>{const o=await reset('?prefix=alternate');assert.equal(o.fields.filter(f=>f.kind==='autocomplete').length,2);assert.equal((await school(o)).complete,true);});
 await check('multi-select stays unsupported even while empty',async()=>{const o=await reset('?multi=1');assert.equal(o.fields.filter(f=>f.kind==='autocomplete').length,0);assert.equal(o.fields.filter(f=>f.kind==='unsupported-combobox').length,2);});
 await check('extension keeps search controls unsupported',async()=>{await reset();const o=await h.bridge.request({op:'inspect'});assert.equal(o.fields.filter(f=>f.kind==='unsupported-combobox').length,2);});
 await check('raw source bindings plus repeated search template complete 10 targets',async()=>{
   await reset();const session=await createDocumentSession({sourcePath:`${projectRoot}/prototype/fixtures/documents/framework-candidate.md`,request});const {source,page}=await session.context();
   const map={'Applicant name':'姓名','Email address':'邮箱','Country of residence':'居住国家','Preferred office city':'意向工作城市','Qualification level':'学历层次','Institution':'学校','Subject':'专业','Personal statement':'个人介绍'};
   const bindings=Object.fromEntries(page.fields.map(f=>[f.ref,source.entries.find(e=>e.label===map[f.label]&&(!f.group||e.context.endsWith('第一段教育经历'))).id]));
   const repeats=Object.fromEntries(page.fields.filter(f=>f.group==='Education 1').map(f=>[f.ref,source.entries.find(e=>e.label===map[f.label]&&e.context.endsWith('第二段教育经历')).id]));
   const r=await session.apply({url:page.url,bindings,repeatGroups:[{templateGroup:'Education 1',expectGroup:'Education 2',controlRef:page.controls[0].ref,bindings:repeats}]});assert.equal(r.complete,true,JSON.stringify(r));assert.equal(r.evidence.length,10);
   const state=await h.page.evaluate(()=>({data:window.applicationState,validation:window.validationState,submits:window.submissionCount,searches:window.searchRequests}));
   assert.deepEqual(state.data,{fullName:'林示例',email:'candidate@example.test',country:'cn',city:'hz',degree:'pg',schools:[{school:'school-south',major:'软件工程'},{school:'school-north',major:'计算机科学'}],summary:source.entries.find(e=>e.label==='个人介绍').value});assert.equal(state.validation.pending,false);assert.equal(state.submits,0);assert.equal(state.searches.length,3);return{targets:10,elapsedMs:r.elapsedMs,searches:state.searches.length};
 });
}finally{await h.close();await writeFile(`${projectRoot}/prototype/reports/${process.env.AFA_VALIDATION_MODE==='guard'?'guard-':''}search-checks.json`,JSON.stringify({date:new Date().toISOString(),component:'react-select@5.10.2',results},null,2));}
if(results.some(r=>!r.passed))process.exitCode=1;
